In [1]:
%pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp39-cp39-macosx_11_0_arm64.whl (11.3 MB)
Requirement already satisfied: numpy>=1.22.4 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pandas
Successfully installed pandas-2.2.3

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
dataset_name: str = "BoolQ/train.jsonl"

In [7]:
from os.path import abspath, join

dataset_path: str = join(abspath(""), "..", "datasets", dataset_name)
dataset_path

'/Users/manuel/PersonalProjects/thesis/notebooks/../datasets/BoolQ/train.jsonl'

In [11]:
from json import loads
from typing import List, Dict, Any

with open(dataset_path, "r") as file:
    records: List[Dict[str, Any]] = [loads(e) for e in file]
print(f"Found {len(records)} records")

Found 9427 records

In [12]:
import pandas as pd

dataframe: pd.DataFrame = pd.DataFrame(records)
dataframe.head()

,question,passage,idx,label
0,do iran and afghanistan speak the same language,"Persian language -- Persian (/ˈpɜːrʒən, -ʃən/)...",0,True
1,do good samaritan laws protect those who help ...,Good Samaritan law -- Good Samaritan laws offe...,1,True
2,is windows movie maker part of windows essentials,Windows Movie Maker -- Windows Movie Maker (fo...,2,True
3,is confectionary sugar the same as powdered sugar,"Powdered sugar -- Powdered sugar, also called ...",3,True
4,is elder scrolls online the same as skyrim,The Elder Scrolls Online -- As with other game...,4,False

In [13]:
sampled_dataframe: pd.DataFrame = dataframe.sample(n=500)
sampled_dataframe.head()

,question,passage,idx,label
933,is gram flour and chickpea flour the same,Gram flour -- Gram flour or chickpea flour or ...,933,True
3094,is to catch a predator still on tv,To Catch a Predator -- The series premiered in...,3094,False
7447,is black mirror season 4 episode 5 in black an...,Metalhead (Black Mirror) -- ``Metalhead'' is t...,7447,True
7261,are ashley williams and kimberly williams pais...,Ashley Williams (actress) -- Williams was born...,7261,True
4946,is there a difference in 2 stroke oil,"Two-stroke oil -- Unlike a four-stroke engine,...",4946,True

In [22]:
from json import dumps

sampled_records: List[Dict[str, Any]] = sampled_dataframe.to_dict(orient="records")
sampled_records.sort(key=lambda r: r["idx"])
sampled_records_jsonl: List[str] = [dumps(record) for record in sampled_records]
sampled_records_jsonl[0]

'{"question": "you can tell a lot about a person by how they treat their waiter", "passage": "Waiter Rule -- The Waiter Rule refers to a common belief that one\'s true character can be gleaned from how one treats staff or service workers, such as a ``waiter\'\'. The rule was one of William H Swanson\'s 33 Unwritten Rules of Management, copied from Dave Barry\'s version ``If someone is nice to you but rude to the waiter, they are not a nice person.\'\'", "idx": 63, "label": true}'

In [24]:
destination_path: str = "/".join([d for d in dataset_path.split("/")[:-1]]) + "/sampled.jsonl"
destination_path

'/Users/manuel/PersonalProjects/thesis/notebooks/../datasets/BoolQ/sampled.jsonl'

In [26]:
with open(destination_path, "w") as file:
    file.write("\n".join(sampled_records_jsonl))