In [13]:
%pip install pandas

Requirement already satisfied: pandas in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: tzdata>=2022.7 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [14]:
dataset_name: str = "RTE/train.jsonl"

In [15]:
from os.path import abspath, join

dataset_path: str = join(abspath(""), "..", "..", "datasets", dataset_name)
dataset_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/RTE/train.jsonl'

In [16]:
from json import loads
from typing import List, Dict, Any

with open(dataset_path, "r") as file:
    records: List[Dict[str, Any]] = [loads(e) for e in file]
print(f"Found {len(records)} records")

Found 2490 records

In [17]:
import pandas as pd

dataframe: pd.DataFrame = pd.DataFrame(records)
dataframe.head()

,premise,hypothesis,label,idx
0,No Weapons of Mass Destruction Found in Iraq Yet.,Weapons of Mass Destruction Found in Iraq.,not_entailment,0
1,"A place of sorrow, after Pope John Paul II die...",Pope Benedict XVI is the new leader of the Rom...,entailment,1
2,Herceptin was already approved to treat the si...,Herceptin can be used to treat breast cancer.,entailment,2
3,"Judie Vivian, chief executive at ProMedica, a ...",The previous name of Ho Chi Minh City was Saigon.,entailment,3
4,A man is due in court later charged with the m...,Paul Stewart Hutchinson is accused of having s...,not_entailment,4

In [18]:
sampled_dataframe: pd.DataFrame = dataframe.sample(n=500)
sampled_dataframe.head()

,premise,hypothesis,label,idx
741,"In an interview this week, the president said ...",Dick Cheney is Vice President of the Defense S...,not_entailment,741
1300,"They were killed on the same day, in the same ...",Adrianna Bachan lived in the USC campus.,not_entailment,1300
2021,"Sirhan Sirhan, a Jordanian immigrant, was conv...",Sirhan Sirhan killed Kennedy.,entailment,2021
658,Ecuador has received short shrift in U.S. poli...,Peru debates border region with Ecuador.,not_entailment,658
267,To promote The Simpsons Movie that will be rel...,The Simpsons is a show broadcast in America.,entailment,267

In [19]:
from json import dumps

sampled_records: List[Dict[str, Any]] = sampled_dataframe.to_dict(orient="records")
sampled_records.sort(key=lambda r: r["idx"])
sampled_records_jsonl: List[str] = [dumps(record) for record in sampled_records]
sampled_records_jsonl[0]

'{"premise": "A man is due in court later charged with the murder 26 years ago of a teenager whose case was the first to be featured on BBC One\'s Crimewatch. Colette Aram, 16, was walking to her boyfriend\'s house in Keyworth, Nottinghamshire, on 30 October 1983 when she disappeared. Her body was later found in a field close to her home. Paul Stewart Hutchinson, 50, has been charged with murder and is due before Nottingham magistrates later.", "hypothesis": "Paul Stewart Hutchinson is accused of having stabbed a girl.", "label": "not_entailment", "idx": 4}'

In [20]:
destination_path: str = "/".join([d for d in dataset_path.split("/")[:-1]]) + "/sampled.jsonl"
destination_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/RTE/sampled.jsonl'

In [21]:
with open(destination_path, "w") as file:
    file.write("\n".join(sampled_records_jsonl))