In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: tzdata>=2022.7 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
dataset_name: str = "WiC/train.jsonl"

In [3]:
from os.path import abspath, join

dataset_path: str = join(abspath(""), "..", "..", "datasets", dataset_name)
dataset_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/WiC/train.jsonl'

In [4]:
from json import loads
from typing import List, Dict, Any

with open(dataset_path, "r") as file:
    records: List[Dict[str, Any]] = [loads(e) for e in file]
print(f"Found {len(records)} records")

Found 5428 records

In [5]:
import pandas as pd

dataframe: pd.DataFrame = pd.DataFrame(records)
dataframe.head()

,word,sentence1,sentence2,idx,label,start1,start2,end1,end2,version
0,place,Do you want to come over to my place later?,A political system with no place for the less ...,0,False,31,27,36,32,1.1
1,approach,Approach a task.,To approach the city.,1,False,0,3,8,11,1.1
2,run,Run rogue.,She ran 10 miles that day.,2,False,0,4,3,7,1.1
3,hold,The general ordered the colonel to hold his po...,Hold the taxi.,3,True,35,0,39,4,1.1
4,summer,We like to summer in the Mediterranean.,We summered in Kashmir.,4,True,11,3,17,11,1.1

In [6]:
sampled_dataframe: pd.DataFrame = dataframe.sample(n=500)
sampled_dataframe.head()

,word,sentence1,sentence2,idx,label,start1,start2,end1,end2,version
2856,strike,Strike a medal.,Strike coins.,2856,True,0,0,6,6,1.1
184,give,Give thought to.,The roof finally gave under the weight of the ...,184,False,0,17,4,21,1.1
178,strike,We must strike the enemy's oil fields.,"In the fifth inning, the Giants struck, sendin...",178,True,8,32,14,38,1.1
784,wash,He managed to wash out the stains.,"The car is so dirty, we need to wash it.",784,True,14,32,18,36,1.1
1019,game,He's in the plumbing game.,The game is 6 all.,1019,False,21,4,25,8,1.1

In [7]:
from json import dumps

sampled_records: List[Dict[str, Any]] = sampled_dataframe.to_dict(orient="records")
sampled_records.sort(key=lambda r: r["idx"])
sampled_records_jsonl: List[str] = [dumps(record) for record in sampled_records]
sampled_records_jsonl[0]

'{"word": "head", "sentence1": "His horse won by a head.", "sentence2": "He is two heads taller than his little sister.", "idx": 5, "label": true, "start1": 19, "start2": 10, "end1": 23, "end2": 15, "version": 1.1}'

In [8]:
destination_path: str = "/".join([d for d in dataset_path.split("/")[:-1]]) + "/sampled.jsonl"
destination_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/WiC/sampled.jsonl'

In [9]:
with open(destination_path, "w") as file:
    file.write("\n".join(sampled_records_jsonl))