In [1]:
%pip install pandas

Looking in indexes: http://dev:****@nexus-leitha.servizi.gr-u.it/repository/leitha_python_all/simple
Requirement already satisfied: pandas in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (2.2.3)
Requirement already satisfied: pytz>=2020.1 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
dataset_name: str = "COPA/train.jsonl"

In [3]:
from os.path import abspath, join

dataset_path: str = join(abspath(""), "..", "..", "datasets", dataset_name)
dataset_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/COPA/train.jsonl'

In [4]:
from json import loads
from typing import List, Dict, Any

with open(dataset_path, "r") as file:
    records: List[Dict[str, Any]] = [loads(e) for e in file]
print(f"Found {len(records)} records")

Found 400 records

In [5]:
import pandas as pd

dataframe: pd.DataFrame = pd.DataFrame(records)
dataframe.head()

,premise,choice1,choice2,question,label,idx
0,My body cast a shadow over the grass.,The sun was rising.,The grass was cut.,cause,0,0
1,The woman tolerated her friend's difficult beh...,The woman knew her friend was going through a ...,The woman felt that her friend took advantage ...,cause,0,1
2,The women met for coffee.,The cafe reopened in a new location.,They wanted to catch up with each other.,cause,1,2
3,The runner wore shorts.,The forecast predicted high temperatures.,She planned to run along the beach.,cause,0,3
4,The guests of the party hid behind the couch.,It was a surprise party.,It was a birthday party.,cause,0,4

In [7]:
len(dataframe)

400

In [8]:
if len(dataframe) >= 500:
    sampled_dataframe: pd.DataFrame = dataframe.sample(n=500)
else:
    sampled_dataframe = dataframe
sampled_dataframe.head()

,premise,choice1,choice2,question,label,idx
0,My body cast a shadow over the grass.,The sun was rising.,The grass was cut.,cause,0,0
1,The woman tolerated her friend's difficult beh...,The woman knew her friend was going through a ...,The woman felt that her friend took advantage ...,cause,0,1
2,The women met for coffee.,The cafe reopened in a new location.,They wanted to catch up with each other.,cause,1,2
3,The runner wore shorts.,The forecast predicted high temperatures.,She planned to run along the beach.,cause,0,3
4,The guests of the party hid behind the couch.,It was a surprise party.,It was a birthday party.,cause,0,4

In [9]:
from json import dumps

sampled_records: List[Dict[str, Any]] = sampled_dataframe.to_dict(orient="records")
sampled_records.sort(key=lambda r: r["idx"])
sampled_records_jsonl: List[str] = [dumps(record) for record in sampled_records]
sampled_records_jsonl[0]

'{"premise": "My body cast a shadow over the grass.", "choice1": "The sun was rising.", "choice2": "The grass was cut.", "question": "cause", "label": 0, "idx": 0}'

In [10]:
destination_path: str = "/".join([d for d in dataset_path.split("/")[:-1]]) + "/sampled.jsonl"
destination_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/COPA/sampled.jsonl'

In [11]:
with open(destination_path, "w") as file:
    file.write("\n".join(sampled_records_jsonl))